#!/usr/bin/env bash
# Display subdomain information

display_info() {
	lastTwoArgs="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1)"
	record_type="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')"
	ip="$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')"
	echo "The subdomain $2 is a $record_type record and points to $ip"
}

if [ $# == 1 ];
then
	for subdomain in www lb-01 web-01 web-02; do
		display_info "$1" "$subdomain"
	done
elif [ $# == 2 ];
then
	display_info "$1" "$2"
fi