#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error-404.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
    error_page 404 /error-404.html;
    location = /error-404.html{
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx start
